apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: target-nginx
  name: target-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: target-nginx
  template:
    metadata:
      labels:
        app: target-nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: target-nginx
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
          limits:
            cpu: 300m
            memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: target-nginx-svc
spec:
  type: NodePort
  selector:
    app: target-nginx
  ports:
  - port: 80
    targetPort: 80