apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: target-nginx-hpa
spec:
  minReplicas: 1
  maxReplicas: 6
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: target-nginx
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        averageUtilization: 50
        type: Utilization